# Stage 1: Build the plugin
FROM maven:3.9-eclipse-temurin-21 AS builder

WORKDIR /app

RUN git clone https://github.com/cinezy/keycloak-event-listener-kafka.git . && mvn clean package -DskipTests

# Stage 2: Setup Keycloak
FROM quay.io/keycloak/keycloak:26.1.4
COPY --from=builder /app/target/keycloak-event-listener-kafka-*.jar /opt/keycloak/providers/

# Build for optimization
RUN /opt/keycloak/bin/kc.sh build

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]