server:
  port: 8081
spring:
  application:
    name: auths
  datasource:
    url: jdbc:postgresql://postgres_user:5432/jemittor_user_service
    username: ${UserService_DB_USER}
    password: ${UserService_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8001/realms/Jemittor
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: jemittor-user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer